"""Create db

Revision ID: 80fadf40fb89
Revises:
Create Date: 2024-06-27 07:12:23.523255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80fadf40fb89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('role', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('role')
    )
    op.create_table(
        'providers',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table(
        'users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('login', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('first_name', sa.String(length=50), nullable=True),
        sa.Column('last_name', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('login')
    )
    op.create_table(
        'login_history',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('provider_id', sa.Integer(), nullable=False),
        sa.Column('logged_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
        sa.PrimaryKeyConstraint('id', 'logged_at'),
        sa.UniqueConstraint('id', 'logged_at'),

        postgresql_partition_by='RANGE (logged_at)'
    )

    op.execute("""CREATE TABLE login_history01_04 PARTITION OF login_history
               FOR VALUES FROM ('2024-01-01') TO ('2024-05-01');""")

    op.execute("""CREATE TABLE login_history05_08 PARTITION OF login_history
               FOR VALUES FROM ('2024-05-01') TO ('2024-09-01');""")

    op.execute("""CREATE TABLE login_history09_12 PARTITION OF login_history
               FOR VALUES FROM ('2024-09-01') TO ('2025-01-01');""")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_history')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('providers')
    # ### end Alembic commands ###
